//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSimpleWebgrid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        public Club()
        {
            this.StdClubs = new HashSet<StdClub>();
        }
    
        public string ClubNo { get; set; }
        public string CName { get; set; }
        public string CPurpose { get; set; }
        public Nullable<decimal> CBudget { get; set; }
        public Nullable<decimal> CActual { get; set; }
    
        public virtual ICollection<StdClub> StdClubs { get; set; }
    }
}
