//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSimpleWebgrid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Offerings = new HashSet<Offering>();
        }
    
        public string CourseNo { get; set; }
        public string CrsDesc { get; set; }
        public Nullable<int> CrsUnits { get; set; }
    
        public virtual ICollection<Offering> Offerings { get; set; }
    }
}
