//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSimpleWebgrid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int OfferNo { get; set; }
        public string StdNo { get; set; }
        public Nullable<decimal> EnrGrade { get; set; }
    
        public virtual Offering Offering { get; set; }
        public virtual Student Student { get; set; }
    }
}
