//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSimpleWebgrid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
        public Faculty()
        {
            this.Offerings = new HashSet<Offering>();
            this.Faculty1 = new HashSet<Faculty>();
        }
    
        public string FacNo { get; set; }
        public string FacFirstName { get; set; }
        public string FacLastName { get; set; }
        public string FacCity { get; set; }
        public string FacState { get; set; }
        public string FacDept { get; set; }
        public string FacRank { get; set; }
        public Nullable<decimal> FacSalary { get; set; }
        public string FacSupervisor { get; set; }
        public Nullable<System.DateTime> FacHireDate { get; set; }
        public string FacZipCode { get; set; }
    
        public virtual ICollection<Offering> Offerings { get; set; }
        public virtual ICollection<Faculty> Faculty1 { get; set; }
        public virtual Faculty Faculty2 { get; set; }
    }
}
