//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSimpleWebgrid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public string StdNo { get; set; }
        public string StdFirstName { get; set; }
        public string StdLastName { get; set; }
        public string StdCity { get; set; }
        public string StdState { get; set; }
        public string StdZip { get; set; }
        public string StdMajor { get; set; }
        public string StdClass { get; set; }
        public Nullable<decimal> StdGPA { get; set; }
    
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}
